sudo: required

services:
  - docker

before_install:
  - docker build -t react-web -f Dockerfile.dev .

script:
  - docker run react-web npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'react-web'
  env: 'react-web-env'
  bucket_name: 'elasticbeanstalk-us-west-2'
  buket_path: 'react-web'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'

